---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: "$IMAGE"
          ports:
           - containerPort: 80
          env:
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_NAME
              value: "$DB_NAME"
            - name: DB_USER
              value: "$DB_USER"
            - name: DB_PASSWORD
              value: "$DB_PASSWORD"
---
apiVersion: v1
kind: Service
metadata:
  name: internal-webapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-external-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: "$NAMESPACE"
spec:
  rules:
    - host: app.$NAMESPACE.com
      http:
        paths:
          - backend:
              serviceName: webapp-external-service
              servicePort: 80