# create amazon-cloudwatch namespace
apiVersion: v1
kind: Namespace
metadata:
  name: "$NAMESPACE"
  labels:
    name: "$NAMESPACE"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: "$NAMESPACE"
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: container-app
          image: "$IMAGE"
          ports:
           - containerPort: 80
          env:
            - name: DB_HOST
              value: "$DB_HOST"
            - name: DB_NAME
              value: "$DB_NAME"
            - name: DB_USER
              value: "$DB_USER"
            - name: DB_PASSWORD
              value: "$DB_PASSWORD"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: internal-webapp-service
  namespace: "$NAMESPACE"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-external-service
  namespace: "$NAMESPACE"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webapp-hpa
  namespace: "$NAMESPACE"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50