version: '3'
networks:
  bridge:
    driver: bridge
services:
  web:
    build: .
    container_name: flask-webapp
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=SSpassword
      - DB_HOST=postgres
    volumes:
      - ./app:/app
    ports:
      - "80:5000"
    depends_on:
      - postgres
    networks:
      - bridge
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "weather", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_PASSWORD=SSpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=weather
    ports:
      - "5432:5432"
    networks:
      - bridge